### ISSUE TITLE
take in MediaStream as `input`, stop using `getusermedia`

### ISSUE THREAD

**Issue by ahdinosaur** [livejs/read-audio#3]
so browser version is synchronous as well.

this will be a breaking change.

**Comment by binarykitchen** [comment]
how then can you convert the data getUserMedia produces to a MediaStream?

**Comment by ahdinosaur** [comment]
[getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia) should return a [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_API#LocalMediaStream), which can then be converted to an [MediaStreamAudioSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioSourceNode) with [AudioContext.createMediaStreamSource()](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource). [the existing code does this](https://github.com/livejs/read-audio/blob/master/browser.js#L47), the plan now is to [remove getUserMedia](https://github.com/livejs/read-audio/blob/master/browser.js#L40-L44) from this module so a `read-audio` consumer must get the media stream themselves and then `read-audio` can always synchronously return the [`ndsamples`](https://github.com/ahdinosaur/ndsamples) stream.

**Comment by binarykitchen** [comment]
have you already made any progress?

**Comment by ahdinosaur** [comment]
ahh, didn't realize you were waiting on me. [done](https://github.com/livejs/read-audio/commit/6a083b2eaa8aa749e69db13c3483deee2acc1c4a). :smiley_cat:

**Comment by binarykitchen** [comment]
cool, will check that out in the next days for my www.videomail.io project
